### ISSUE TITLE
ImportError: R Package (k)pcalg/RCIT is not available.

### ISSUE THREAD

**Issue by jinxtan** [FenTechSolutions/CausalDiscoveryToolbox#148]
No GPU automatically detected. Setting SETTINGS.GPU to 0, and SETTINGS.NJOBS to cpu_count.
Traceback (most recent call last):
  File "D:\anaconda3\envs\py37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\pycharm\PyCharm 2022.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\pycharm\PyCharm 2022.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\onedrive_st\OneDrive - st.nuc.edu.cn\project\data_synthesis\ceshi.py", line 14, in <module>
    pc_output = PC().create_graph_from_data(data)
  File "D:\anaconda3\envs\py37\lib\site-packages\cdt\causality\graph\PC.py", line 176, in __init__
    raise ImportError("R Package (k)pcalg/RCIT is not available. "
ImportError: R Package (k)pcalg/RCIT is not available. RCIT has to be installed from https://github.com/Diviyan-Kalainathan/RCIT

![image](https://user-images.githubusercontent.com/38872112/197321042-d7e0af70-e0a8-47cf-b47b-91f5b6d34c0d.png)
But I have installed these packages! I need your help

**Comment by jinxtan** [comment]
I've solved the bug!

**Comment by Jiuyue213** [comment]
> I've solved the bug!

how?

**Comment by Yukang-Lin** [comment]
> I've solved the bug!

I meet the same issue, could you please tell me how you solve that!
