### ISSUE TITLE
Trying to run GES

### ISSUE THREAD

**Issue by ManishaSharma-1** [FenTechSolutions/CausalDiscoveryToolbox#82]
Hi Team, 
I am getting this error:

R Python Error Output 
-----------------------

[Errno 2] File /tmp/cdt_ges_2755b76f-a9cc-40ad-b058-1b1c01cc5c21/result.csv does not exist: '/tmp/cdt_ges_2755b76f-a9cc-40ad-b058-1b1c01cc5c21/result.csv'

Trying to run below snippet

import networkx as nx
from cdt.causality.graph import GES
from cdt.data import load_dataset
data, graph = load_dataset("sachs")
obj = GES()
#The predict() method works without a graph, or with a
#directed or udirected graph provided as an input
output = obj.predict(data)    #No graph provided as an argument

output = obj.predict(data, nx.Graph(graph))  #With an undirected graph

output = obj.predict(data, graph)  #With a directed graph

#To view the graph created, run the below commands:
nx.draw_networkx(output, font_size=8)
plt.show()

**Comment by Diviyan-Kalainathan** [comment]
Hello  !  Sorry for the delay

Which version of the code are you running ? Could you update to the latest version ? (it includes more detailed traceback)

Best,
Diviyan

**Comment by dcuoliveira** [comment]
O had a similar issue today. The error is as follows

```
R Python Error Output 
-----------------------

[Errno 2] No such file or directory: '/var/folders/5b/ctj6f2bj6z55_qhnvbh2xgy80000gn/T/cdt_bnlearn_f63747a9-c5d2-4560-a821-8813a38ee9ab/result.csv'
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-39-908d0536cbd1> in <module>
      1 obj = IAMB()
----> 2 output = obj.predict(data)

/opt/anaconda3/lib/python3.8/site-packages/cdt/causality/graph/model.py in predict(self, df_data, graph, **kwargs)
     61         """
     62         if graph is None:
---> 63             return self.create_graph_from_data(df_data, **kwargs)
     64         elif isinstance(graph, nx.DiGraph):
     65             return self.orient_directed_graph(df_data, graph, **kwargs)

/opt/anaconda3/lib/python3.8/site-packages/cdt/causality/graph/bnlearn.py in create_graph_from_data(self, data)
    225         data2 = data.copy()
    226         data2.columns = [i for i in range(data.shape[1])]
--> 227         results = self._run_bnlearn(data2, verbose=self.verbose)
    228         graph = nx.DiGraph()
    229         graph.add_nodes_from(['X' + str(i) for i in range(data.shape[1])])

/opt/anaconda3/lib/python3.8/site-packages/cdt/causality/graph/bnlearn.py in _run_bnlearn(self, data, whitelist, blacklist, verbose)
    262         except Exception as e:
    263             rmtree(run_dir)
--> 264             raise e
    265         except KeyboardInterrupt:
    266             rmtree(run_dir)

/opt/anaconda3/lib/python3.8/site-packages/cdt/causality/graph/bnlearn.py in _run_bnlearn(self, data, whitelist, blacklist, verbose)
    257                 self.arguments['{E_WHITEL}'] = 'FALSE'
    258 
--> 259             bnlearn_result = launch_R_script(Path("{}/R_templates/bnlearn.R".format(os.path.dirname(os.path.realpath(__file__)))),
    260                                              self.arguments, output_function=retrieve_result, verbose=verbose)
    261         # Cleanup

/opt/anaconda3/lib/python3.8/site-packages/cdt/utils/R.py in launch_R_script(template, arguments, output_function, verbose, debug)
    219                 print("\nR Python Error Output \n-----------------------\n")
    220                 print(e)
--> 221                 raise RuntimeError("RProcessError \nR Process Error Output \n-----------------------\n" + str(err, "ISO-8859-1")) from None
    222             print("\nR Python Error Output \n-----------------------\n")
    223             print(e)

RuntimeError: RProcessError 
R Process Error Output 
-----------------------
```

I tried to set the Rscript path as follows:

```
import cdt
cdt.SETTINGS.rpath = "/Volumes/disk0s2/Library/Frameworks/R.framework/Resources/bin/R"
```
Im running the coding using VScode and Macbook with the following config:

```
MacOS: BigSur 11.2
Python: 3.8.5
R: 4.0.3 
```

**Comment by maxwellreynolds** [comment]
I am also running into this issue with GES from the tutorial. Running version 0.5.23 on Mac

**Comment by Talivni** [comment]
I'm having the same issue

**Comment by francescomontagna** [comment]
I have the same issue

**Comment by diviyank** [comment]
This is strange, i'm not able to replicate this issue, are you using cdt 0.6.0?

**Comment by njbamboo** [comment]
My envs are:
- Apple Mac mini M1 chip
- macOS Monterey 12.6
- Python 3.10
- cdt 0.60
- R packages cdt needed 
All (python, cdt, and R packages) have same versions as those in Windows10
In my case, when I ran the tutorial scripts on my Windows10, it is no error. But when I ran it on my Apple mini M1, it is a different story
Tutorial scripts:
'''
model = cdt.causality.graph.GES()
output_graph = model.predict(data, new_skeleton)
print(nx.adjacency_matrix(output_graph).todense())
'''

it gave me the below error messages:

'''
Output:
GES is ran on the skeleton of the given graph.
adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
ARGUMENT '/var/folders/j6/9thfps154wzblxd7qf8bzmwr0000gn/T/cdt_R_script_ed9d3c4b-ac0b-41be-aab0-23896d0c159c/instance_ges.R' __ignored__
...
R Python Error Output 
-----------------------

[Errno 2] No such file or directory: '/var/folders/j6/9thfps154wzblxd7qf8bzmwr0000gn/T/cdt_ges_a1452f34-d677-4e4e-bba1-51f028a98c9c/result.csv'

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [15], line 2
      1 model = cdt.causality.graph.GES()
----> 2 output_graph = model.predict(data, new_skeleton)
      3 print(nx.adjacency_matrix(output_graph).todense())

File /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/cdt/causality/graph/model.py:65, in GraphModel.predict(self, df_data, graph, **kwargs)
     63     return self.create_graph_from_data(df_data, **kwargs)
     64 elif isinstance(graph, nx.DiGraph):
---> 65     return self.orient_directed_graph(df_data, graph, **kwargs)
     66 elif isinstance(graph, nx.Graph):
     67     return self.orient_undirected_graph(df_data, graph, **kwargs)

File /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/cdt/causality/graph/GES.py:159, in GES.orient_directed_graph(self, data, graph)
    149 """Run GES on a directed graph.
    150 
    151 Args:
   (...)
    156     networkx.DiGraph: Solution given by the GES algorithm.
    157 """
    158 warnings.warn("GES is ran on the skeleton of the given graph.")
--> 159 return self.orient_undirected_graph(data, nx.Graph(graph))

File /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/cdt/causality/graph/GES.py:143, in GES.orient_undirected_graph(self, data, graph)
...
--> 224         raise RuntimeError("RProcessError ") from None
    226 if not debug:
    227     rmtree(base_dir)

RuntimeError: RProcessError

**Comment by Jiuyue213** [comment]
I‘m having the same issue,so how should I do?  
Below are all the bug I meet running in jupyterbook,  and I also attach my code and my env packages below.  please help me, thanks.

my code:
```
import cdt
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt
from cdt.causality.graph import PC

# Load the data
data = pd.read_csv('http://www.causality.inf.ethz.ch/data/lucas0_train.csv')

# Infer the causal diagram
pc_output = PC().create_graph_from_data(data)

# Visualize the diagram
nx.draw_networkx(pc_output)
plt.show()
```

my bug:
```
R Python Error Output 
-----------------------

[Errno 2] No such file or directory: 'C:\\Users\\Jiuyue\\AppData\\Local\\Temp\\cdt_pc_dccede31-26aa-4f57-a35b-5aeb44deaf6b\\result.csv'
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [13], line 11
      8 data = pd.read_csv('http://www.causality.inf.ethz.ch/data/lucas0_train.csv')
     10 # Infer the causal diagram
---> 11 pc_output = PC().create_graph_from_data(data)
     13 # Visualize the diagram
     14 nx.draw_networkx(pc_output)

File D:\anaconda3\envs\dowhy\lib\site-packages\cdt\causality\graph\PC.py:278, in PC.create_graph_from_data(self, data, **kwargs)
    275 self.arguments['{NJOBS}'] = str(self.njobs)
    276 self.arguments['{VERBOSE}'] = str(self.verbose).upper()
--> 278 results = self._run_pc(data, verbose=self.verbose)
    280 return nx.relabel_nodes(nx.DiGraph(results),
    281                         {idx: i for idx, i in enumerate(data.columns)})

File D:\anaconda3\envs\dowhy\lib\site-packages\cdt\causality\graph\PC.py:315, in PC._run_pc(self, data, fixedEdges, fixedGaps, verbose)
    313 except Exception as e:
    314     rmtree(run_dir)
--> 315     raise e
    316 except KeyboardInterrupt:
    317     rmtree(run_dir)

File D:\anaconda3\envs\dowhy\lib\site-packages\cdt\causality\graph\PC.py:310, in PC._run_pc(self, data, fixedEdges, fixedGaps, verbose)
    307     else:
    308         self.arguments['{E_EDGES}'] = 'FALSE'
--> 310     pc_result = launch_R_script(Path("{}/R_templates/pc.R".format(os.path.dirname(os.path.realpath(__file__)))),
    311                                 self.arguments, output_function=retrieve_result, verbose=verbose)
    312 # Cleanup
    313 except Exception as e:

File D:\anaconda3\envs\dowhy\lib\site-packages\cdt\utils\R.py:221, in launch_R_script(template, arguments, output_function, verbose, debug)
    219     print("\nR Python Error Output \n-----------------------\n")
    220     print(e)
--> 221     raise RuntimeError("RProcessError \nR Process Error Output \n-----------------------\n" + str(err, "ISO-8859-1")) from None
    222 print("\nR Python Error Output \n-----------------------\n")
    223 print(e)

RuntimeError: RProcessError 
R Process Error Output 
-----------------------
Loading required package: momentchi2
Loading required package: MASS
Error: invalid multibyte character in parser at line 1
Execution halted
```



below are all my packages and their versions in my env.

```
asttokens          2.0.8
backcall           0.2.0
cdt                0.6.0
certifi            2022.9.24
charset-normalizer 2.1.1
colorama           0.4.6
contourpy          1.0.6
cycler             0.11.0
debugpy            1.6.3
decorator          5.1.1
dowhy              0.8
entrypoints        0.4
executing          1.2.0
fonttools          4.38.0
GPUtil             1.4.0
idna               3.4
ipykernel          6.17.1
ipython            8.5.0
jedi               0.18.1
joblib             1.2.0
jupyter_client     7.3.5
jupyter-core       4.11.1
kiwisolver         1.4.4
matplotlib         3.6.2
matplotlib-inline  0.1.6
mpmath             1.2.1
nest-asyncio       1.5.5
networkx           2.8.8
numpy              1.23.4
packaging          21.3
pandas             1.5.1
parso              0.8.3
patsy              0.5.3
pickleshare        0.7.5
Pillow             9.3.0
pip                22.2.2
prompt-toolkit     3.0.31
psutil             5.9.2
pure-eval          0.2.2
pydot              1.4.2
Pygments           2.13.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.6
pywin32            305
pyzmq              24.0.1
requests           2.28.1
scikit-learn       1.1.3
scipy              1.9.3
setuptools         65.5.0
six                1.16.0
skrebate           0.62
stack-data         0.5.0
statsmodels        0.13.5
sympy              1.11.1
threadpoolctl      3.1.0
torch              1.10.0
tornado            6.2
tqdm               4.64.1
traitlets          5.5.0
typing_extensions  4.4.0
urllib3            1.26.12
wcwidth            0.2.5
wheel              0.37.1
wincertstore       0.2
```

**Comment by chenxiachan** [comment]
My experience is: make sure all columns in your dataframe are in type of float/int. Avoid involving object/str types.

**Comment by DSM-DSM** [comment]
i encounter the same problem when run the following code.
import cdt
from rpy2.robjects.packages import importr

cdt.SETTINGS.rpath = cdt.SETTINGS.rpath = r'C:\Program Files\R\R-4.4.2\bin\Rscript.exe'
data, graph = cdt.data.load_dataset('sachs')
print(data.head())

glasso = cdt.independence.graph.Glasso()
skeleton = glasso.predict(data)
print(skeleton)

import networkx as nx

new_skeleton = cdt.utils.graph.remove_indirect_links(skeleton, alg='aracne')
print(nx.adjacency_matrix(new_skeleton).todense())
print(type(new_skeleton))  # networkx.classes.digraph.DiGraph

print(cdt.__version__)

importr('pcalg')
importr('RCIT')
importr('methods')
importr('kpcalg')
model = cdt.causality.graph.PC()
model.predict(data, new_skeleton) 

The error ocurr at the last line "model.predict(data, new_skeleton)".

**Comment by DSM-DSM** [comment]
i encounter the same problem when run the following code.
```
import cdt
from rpy2.robjects.packages import importr

cdt.SETTINGS.rpath = cdt.SETTINGS.rpath = r'C:\Program Files\R\R-4.4.2\bin\Rscript.exe'
data, graph = cdt.data.load_dataset('sachs')
print(data.head())

glasso = cdt.independence.graph.Glasso()
skeleton = glasso.predict(data)
print(skeleton)

import networkx as nx

new_skeleton = cdt.utils.graph.remove_indirect_links(skeleton, alg='aracne')
print(nx.adjacency_matrix(new_skeleton).todense())
print(type(new_skeleton)) # networkx.classes.digraph.DiGraph

print(cdt.version)

importr('pcalg')
importr('RCIT')
importr('methods')
importr('kpcalg')
model = cdt.causality.graph.PC()
model.predict(data, new_skeleton)
```

The error ocurr at the last line "model.predict(data, new_skeleton)". Here are my error info:
```

PC is ran on the skeleton of the given graph.
R Python Error Output 
-----------------------
[Errno 2] No such file or directory: 'C:\\Users\\Username\\AppData\\Local\\Temp\\cdt_pc_173b6819-1307-4694-ac5a-58b72fbdc55f\\result.csv'
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ef3a75a3f1d>", line 1, in <module>
    runfile('D:\\CausalLearning\\test.py', wdir='D:\\CausalLearning')
  File "D:\PyCharm 2023.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm 2023.3.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\CausalLearning\test.py", line 25, in <module>
    model.predict(data, new_skeleton)
  File "D:\Anaconda3\Lib\site-packages\cdt\causality\graph\model.py", line 65, in predict
    return self.orient_directed_graph(df_data, graph, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\cdt\causality\graph\PC.py", line 259, in orient_directed_graph
    return self.orient_undirected_graph(data, nx.Graph(graph), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\cdt\causality\graph\PC.py", line 238, in orient_undirected_graph
    results = self._run_pc(data, fixedEdges=fe, fixedGaps=fg, verbose=self.verbose)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\cdt\causality\graph\PC.py", line 315, in _run_pc
    raise e
  File "D:\Anaconda3\Lib\site-packages\cdt\causality\graph\PC.py", line 310, in _run_pc
    pc_result = launch_R_script(Path("{}/R_templates/pc.R".format(os.path.dirname(os.path.realpath(__file__)))),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\cdt\utils\R.py", line 221, in launch_R_script
    raise RuntimeError("RProcessError \nR Process Error Output \n-----------------------\n" + str(err, "ISO-8859-1")) from None
RuntimeError: RProcessError 
R Process Error Output 
-----------------------
```

**Comment by diviyank** [comment]
Hello, do you have something after this log?

**Comment by DSM-DSM** [comment]
> Hello, do you have something after this log?

No, and to explain the question explicitly, I upload the code and the result.
I ran the code in my pyhcarm, and here lists some of infomation may help:
python -- 3.11
cdt -- 0.6.0
pandas -- 1.3.5
rpy2 -- 3.5.16
R -- 4.4.2

<img width="1229" alt="屏幕截图 2024-11-17 175727" src="https://github.com/user-attachments/assets/90ce0fe8-e10a-4b2d-ab62-bd757e532bf7">

If there are more infomation needed, please tell me. Thank you for you time!
